# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200310_0847'),
    ]

    operations = [
    ]
