# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200310_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='type1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpye_1', to='shop.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
