# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200311_0154'),
    ]

    operations = [
    ]
